version: 0.2

phases:
  install:
    commands:
      - echo "Installing Serverless"
      - npm install -g serverless@3
  pre_build:
    commands:
      - echo "Installing dependencies..."
      - npm install
  build:
    commands:
      - echo "Building the application..."
      - sls deploy -v -s ${ENV_NAME:-prod}
  post_build:
    commands:
      - echo "Build completed successfully."